import { DebugConfig } from "./types";

export const debugConfig: DebugConfig = {
  hotel: {
    positionX: 0,
    positionY: 0,
    positionZ: 0,
    scaleValue: 30.01,
    rotationX: 0,
    rotationY: -Math.PI / 2,
    rotationZ: 0,
  },
  world: {
    positionX: -11.3,
    positionY: -26.9,
    positionZ: 0.90006,
    scaleValue: 164.01,
    rotationX: 0,
    rotationY: -1.6,
    rotationZ: 0,
  },
  sky: {
    elevation: 3,
    azimuth: 0,
    turbidity: 20,
    rayleigh: 0,
    mieCoefficient: 0.005,
    mieDirectionalG: 0,
  },
  ocean: {
    positionX: 0,
    positionY: -46.4,
    positionZ: 0,
  },
  fog: {
    enabled: true,
    color: "#b1b7b9",
    near: 10,
    far: 2000,
  },
  blueOrb: {
    alwaysVisible: false,
    positionX: 0.5,
    positionY: -6.4,
    positionZ: 3.5,
    scale: 1.2,
    coreColor: "#03a9f4",
    emissiveColor: "#0288d1",
    emissiveIntensity: 2,
    glowColor: "#4fc3f7",
    glowOpacity: 0.3,
    lightIntensity: 2,
    lightDistance: 10,
    floatAmplitude: 0,
    floatSpeed: 0,
    rotationSpeed: 0,
  },
  grass: {
    enabled: false,
    count: 543100,
    spread: 85,
    height: 0.25,
    width: 0.3,
    baseColor: "#38582d",
    swayStrength: 0.12,
    swaySpeed: 1.0,
    positionX: -13,
    positionY: -17,
    positionZ: -6,
  },
  camera: {
    positionX: 0,
    positionY: 0,
    positionZ: 78,
    fov: 50,
    targetX: 45,
    targetY: 0,
    targetZ: 0,
  },
  dissolve: {
    startDistance: 260,
    endDistance: 18,
    worldMaxPoints: 20000,
    worldPointSize: 0.6,
    hotelMaxPoints: 7000,
    hotelPointSize: 0.35,
    skyPointSize: 2,
    oceanPointSize: 2,
    scatterStart: 0,
    modelStart: 0,
    modelEnd: 1,
    skyStart: 0,
    skyEnd: 1,
    oceanStart: 0,
    oceanEnd: 1,
    fogStart: 0,
    fogEnd: 0,
  },
  groundFog: {
    enabled: true,
    color: "#d7dee4",
    density: 0.5,
    height: 1,
    noiseScale: 0.015,
    noiseSeed: 100,
    noiseSpeed: 0.3,
    opacity: 0.5,
    positionX: 0,
    positionY: -15,
    positionZ: 0,
    size: 50,
    segments: 128,
    followCamera: true,
    cameraOffsetY: -5,
  },
  hotelLights: {
    showHelpers: false,
    helperSize: 1,
    light1: {
      enabled: true,
      positionX: 0.10006,
      positionY: 0.21999,
      positionZ: -0.01999,
      color: "#ff8c42",
      intensity: 30,
      power: 200,
      distance: 15,
      decay: 2,
    },
    light2: {
      enabled: true,
      positionX: 0.10006,
      positionY: 0,
      positionZ: -0.0099,
      color: "#ff9f5a",
      intensity: 30,
      power: 200,
      distance: 15,
      decay: 2,
    },
    light3: {
      enabled: true,
      positionX: 0.10006,
      positionY: -0.1299,
      positionZ: -0.0099,
      color: "#ffb366",
      intensity: 30,
      power: 200,
      distance: 15,
      decay: 2,
    },
    light4: {
      enabled: true,
      positionX: 0.14999,
      positionY: -0.4399,
      positionZ: -0.0199,
      color: "#fafb98",
      intensity: 10,
      power: 200,
      distance: 15,
      decay: 2,
    },
  },
  neonSign: {
    enabled: true,
    showHelpers: false,
    helperSize: 0.25,
    verticalSign: {
      enabled: true,
      text: "MOBALTT",
      positionX: 0.01,
      positionY: -0.2,
      positionZ: 0.14,
      rotationY: 1.5784,
      fontSize: 0.04,
      color: "#ff6b35",
      emissiveIntensity: 7.2,
      letterSpacing: 0.02,
    },
    horizontalSign: {
      enabled: true,
      text: "WHISKEY HOTEL",
      positionX: 0.12,
      positionY: -0.37,
      positionZ: -0.02,
      rotationY: 1.5584,
      fontSize: 0.02,
      color: "#ffcc66",
      emissiveIntensity: 3,
    },
    glowIntensity: 5,
    flickerEnabled: true,
    flickerSpeed: 0.7,
    flickerIntensity: 1,
  },
  bloom: {
    enabled: true,
    intensity: 5,
    luminanceThreshold: 1,
    luminanceSmoothing: 0.38,
    radius: 0.15,
  },
};
